name: Sync with Sanguine

on:
  schedule:
    - cron: '0 * * * *'  # This will run the job every hour
  push:
    branches:
      - master

jobs:
  sync:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sanguine-contracts-core
      uses: actions/checkout@v2
      with:
        repository: 'aureliusbtc/sanguine-contracts-core'

    - name: Set Git identity
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
          
  - name: Fetch and split latest contracts-core from Sanguine
    run: |
      git remote add sanguine https://github.com/synapsecns/sanguine.git
      git fetch sanguine master
      git subtree split --prefix=packages/contracts-core -b temp_branch FETCH_HEAD

  - name: Integrate changes and commit
    run: |
      git checkout master
      git reset --hard temp_branch
      GIT_DIFF=$(git diff master..origin/master)
      if [ -n "$GIT_DIFF" ]; then
        git commit -m "Synchronized with Sanguine [skip ci]"
        git push origin master
      fi
