name: Sync with Sanguine

on:
  schedule:
    - cron: '0 * * * *'  # This will run the job every hour
  push:
    branches:
      - master

jobs:
  sync:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sanguine-contracts-core
      uses: actions/checkout@v2
      with:
        repository: 'aureliusbtc/sanguine-contracts-core'

    - name: Set Git identity
          run: |
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"
          
    - name: Fetch latest from Sanguine
      run: |
        git remote add sanguine https://github.com/synapsecns/sanguine.git
        git fetch sanguine
        git checkout master
        git reset --hard sanguine/master
        git subtree split --prefix=packages/contracts-core -b temp_branch
        git checkout master
        git reset --hard temp_branch

    - name: Push changes to sanguine-contracts-core
      run: |
        git commit -m "Synchronized with Sanguine [skip ci]"
        git push origin master
