name: Sync with Sanguine

on:
  schedule:
    - cron: '0 * * * *'  # This will run the job every hour
  push:
    branches:
      - master

jobs:
  sync:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sanguine-contracts-core
      uses: actions/checkout@v2
      with:
        repository: 'aureliusbtc/sanguine-contracts-core'

    - name: Set Git identity
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
          
    - name: Fetch latest from Sanguine
      run: |
        git remote add sanguine https://github.com/synapsecns/sanguine.git
        git fetch sanguine master

    - name: Check folder and split if exists
      run: |
        # Create a temporary branch to check the content without disturbing master
        git checkout -b temp_check FETCH_HEAD
        
        if [ -d "packages/contracts-core" ]; then
          git subtree split --prefix=packages/contracts-core -b temp_branch
          git checkout master
          git reset --hard temp_branch
        else
          echo "Directory packages/contracts-core does not exist in fetched content"
          exit 1
        fi